### ISSUE TITLE
Modify present GitHub Actions workflow to deploy to Netlify

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#105]
## What's the Issue?

The current GitHub Action does nothing more than run ESLint & Prettier to check for common coding styles. As such, it simply standardizes those differences within a CI environment. As for the CD part, that's taken care off of by the Netlify which results in some redundancy.

Netlify's free tier also provides measly 300 build minutes per month which isn't enough for an opensource project to be honest. Hence, we need to delegated the every aspect of the CI/CD pipeline over to GitHub instead. Since GitHub provides a generous 2000 build minutes a month, we won't be running out of it any time soon. And not to forget it's easier for contributors to debug CI/CD issues when the infrastructure is in the same place.

## Possible Solution to the Issue

Possible solution to the issue to simply add another `job` to the current workflow which is configured at [`.github/workflows/main.yml`](https://github.com/developersIndia/website/blob/master/.github/workflows/main.yml).

There quite a few community built GitHub Actions out there to deploy to Netlify & following is an example I picked up from one of those Actions:

```yaml
     # Rest of the workflow contents
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
```

## Resources for Referral

Following are some resources for referral which should help in configuring the workflow further:

- [`nwtgck/netlify-actions`](https://github.com/marketplace/actions/netlify-actions)
- [CI/CD Pipeline with Netlify and GitHub Actions](https://dev.to/dancurtis/ci-cd-pipeline-with-netlify-and-github-actions-bcm)
- [GitHub Actions: How to autodeploy your app](https://blog.logrocket.com/github-actions-how-to-autodeploy-your-app/)

**Comment by afkcodes** [comment]
is the website going to be deployed on netlify ? if so then lets go with vercel

**Comment by Jarmos-san** [comment]
The site was deployed on Vercel initially (check the deployment [environments](https://github.com/developersIndia/website/deployments)) but inviting other users to a team requires a premium fee which is like $40 per month (need further clarification about the quotation). At this we obviously can't afford that price so we went ahead with Netlify instead.

Between the two I personally prefer the former as well even though I've experience using Netlify for quite a while. But regardless since we don't have the funds let's stick with whatever is the cheapest option out there right now. 😅

**Comment by afkcodes** [comment]
no, i think we can do it without that I have been doing with my organization, let's discuss this.

**Comment by Jarmos-san** [comment]
Yes, Vercel does come with added benefits as well which is why I've been moving away from Netlify recently as well.

cc @Bhupesh-V could explain what issues did you face setting up the Vercel org & why we need Netlify instead?

**Comment by Jarmos-san** [comment]
Also @afkcodes we'll be integrating the whole CI/CD pipeline into GitHub Actions eventually, so I really doubt if it matters whether we're using Netlify or Vercel.

**Comment by NiketanG** [comment]
I've managed to set up an action using the netlify-cli for the build and deploy. 
The GitHub actions available mentioned above, and even netlify's own, fail to build the project with necessary plugins (nextjs-plugin-netlify).
Using the cli is better in my opinion as we could swap it out later when changing the provider without much hassle. 
However I need to figure out the caching of the global netlify-cli so we could save some cicd minutes. If anyone has any expertise, I would be thankful for your help

Apart from that the job is mostly done imo.

**Comment by Jarmos-san** [comment]
@NiketanG could you share a lil snippet of what your code looks like?

**Comment by NiketanG** [comment]
> @NiketanG could you share a lil snippet of what your code looks like?

```
name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  runCodeQualityChecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install Prettier & ESLint
        run: npm install prettier eslint

      - name: Format code using Prettier
        run: npm run format

      - name: Lint source code
        run: npm run lint

  # TODO: Run test suite

  runNextBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          
      - name: 🧰 Install dependencies for Next.js Build
        run: npm install
        
      - name: 📦 Run Next.js build to generate the static files
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      
      - name: Deploy
        run: netlify deploy --build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

```
