### ISSUE TITLE
[FEATURE REQUEST]: Add [Light/Dark/System Default] Theme support to the entire site from the beginning itself

### ISSUE THREAD

**Issue by SFM61319** [developersIndia/website#118]
### Feature details?

As the title suggests, it would be easier and better to implement Light/Dark[/System Default] theme in the beginning itself, since the site is very small and still in its initial phase right now.

##### Example
```css
:root,
:root[data-theme="light"] {
  --fg: #000000FF;
  --bg: #FFFFFFFF;
}

@media (prefers-color-scheme: dark) {
  :root {
    --fg: #FFFFFFFF;
    --bg: #000000FF;
  }
}

:root[data-theme="dark"] {
  --fg: #FFFFFFFF;
  --bg: #000000FF;
}

body {
  color: var(--fg);
  background-color: var(--bg);
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
